import "./globals.css";
import type { Metadata } from "next";
import { Inter, Sora } from "next/font/google";
import AuthSession from "../components/provider/AuthSession";
import SideNavbar from "@/components/sidebar";
import Navbar from "@/components/navbar";
import { motion, AnimatePresence } from "framer-motion";
import { usePathname, useRouter } from "next/navigation";
import BottomNav from "@/components/BottomNav";
import UiProvider from "../components/provider/uiProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ABGame",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UiProvider>
          <AuthSession>
            <div className="mb-24">{children}</div>
            <BottomNav />
          </AuthSession>
        </UiProvider>
      </body>
    </html>
  );
}
